---
# handlers file for docker
- name: Add Docker Group
  # become: true
  ansible.builtin.group:
    name: docker
    state: present

- name: Enable Docker Service
  # become: true
  ansible.builtin.systemd:
    name: docker
    enabled: true

- name: Start Docker Service
  # become: true
  ansible.builtin.systemd:
    name: docker
    state: started
