---
# tasks file for nodejs
- name: Download NodeJS
  get_url:
    url: https://nodejs.org/dist/{{ version }}/{{ node }}.tar.xz
    dest: '{{ tmp }}'

- name: Extract NodeJS
  become: true
  unarchive:
    src: '{{ tmp }}'
    dest: /opt
    remote_src: true

- name: Install NodeJS # Create a symbolic link
  become: true
  file:
    src: /opt/{{ node }}/bin/node
    dest: /usr/local/bin/node
    state: link
