---
# tasks file for docker
- name: Get Docker Engine
  # become: true
  ansible.builtin.unarchive:
    src: '{{ docker_download }}'
    dest: /opt/
    remote_src: true

- name: Get Compose N Machine
  # become: true
  ansible.builtin.get_url:
    url: '{{ item.url }}'
    dest: '{{ item.dest }}'
    mode: +x
  loop:
    - { url: '{{ compose_download }}', dest: /opt/docker/docker-compose }
    - { url: '{{ machine_download }}', dest: /opt/docker/docker-machine }

- name: Copy Unit Files
  # become: true
  ansible.builtin.copy:
    src: '{{ item }}'
    dest: /etc/systemd/system/
  loop:
    - docker.service
    - docker.socket
  notify:
    - Add Docker Group
    - Enable Docker Service

- name: Get Binary Files
  # become: true
  ansible.builtin.find:
    paths: /opt/docker/
    file_type: file
  register: binaries

- name: Create Symbolic Links
  # become: true
  ansible.builtin.file:
    src: '{{ item.path }}'
    dest: /usr/bin/{{ item.path | basename }}
    state: link
  loop:
    '{{ binaries.files }}'
  notify:
    - Start Docker Service
